on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build and package
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Create source tarball
        run: tar -czvf src.tar.gz src
      - name: Build package
        uses: toltec-dev/build-action@v1
      - name: Save packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: dist/rm*/*.ipk
      - name: Save repo
        uses: actions/upload-artifact@v3
        with:
          name: rmall
          path: dist/rmall
  test:
    name: Test package
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: rmall
      - uses: Eeems-Org/run-in-remarkable-action@v1
        with:
          setup: |
            set -ex
            echo "src/gz local-rmall file:///opt/tmp/src" > /opt/etc/opkg.conf.d/16-local.conf
          run: |
            set -ex
            echo Y | toltecctl generate-opkg-conf
            opkg update
            opkg install my-app
            # Add steps here to test app
            opkg remove my-app
          path: ${{ steps.download.outputs.download-path }}
