on:
  push:
  pull_request:
jobs:
  build:
    name: Build and package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install toltecmk
        run: pip install toltecmk
      - name: Build package
        run: |
          tar -czvf src.tar.gz src
          toltecmk
      - name: Save packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: release
